### PR TITLE
fix: handling of map entries with omitted key or value

### LINKED ISSUE #843: Map fields with empty string as key are handled incorrectly
protobuf.js version: 6.8.0

UPDATED:
Current codegen for map-fields when string key is empty is incorrect.

ORIGINAL:
Current codegen for map-fields is invalid. It assumes that map keys are non empty (!) strings (!!).

1. Map CAN have empty string as indices.
2. ~~Map CAN be indexed by something different than string...~~

~~Both parsing and JS representation (Object instead of Map) are broken.~~

### LINKED ISSUE #960: map doesn't work for empty values
protobuf.js version: 6.8.3

protobuf.js throws an error when trying to decode any map encoded using google's protobuf for c#

```js
message= Message.decode(buffer);
```

```
Error: invalid wire type 6 at offset 896
    at n.skipType (reader.js:375)
```

### PR DESCRIPTION
**Pull request by schiffermtq**
According to [1], map encoding must be compatible with a repeated message
using indices 1 and 2 for key and value. In particular this implies that
both key and value may be omitted when they are equal to the default
value - which some protobuf implementations like protobuf-c actually do.

The comments in the added testcase are based on the output of
protobuf-inspector [2].

[1] https://developers.google.com/protocol-buffers/docs/proto3#backwards-compatibility
[2] https://github.com/jmendeth/protobuf-inspector

This is a cleaned up version of #1087:
- Added detailed commit message
- Improved coding style
- Added test case

Supersedes #845
Supersedes #1087
Fixes #843
Fixes #960 
Fixes #1087

### CODE REVIEW

File: src/decoder.js [hunk 1]
```diff
@@ -37,22 +37,48 @@ function decoder(mtype) {
...
+                ("k=\"%s\"", types.defaults[field.keyType]);
+            else if (types.defaults[field.keyType] !== undefined) gen
+                ("k=%s", types.defaults[field.keyType]);
+            else gen
+                ("k=null");
+
+            if (type === "string") gen
+                ("value=\"%s\"", types.defaults[type]);
+            else if (types.defaults[type] !== undefined) gen
+                ("value=%s", types.defaults[type]);
```
Comment (johncantrell97) [inline src/decoder.js]: if type === "bytes" then this tries to insert the default value of an empty array with %s and it ends up inserting empty string "" instead of "[]".  This is because %s calls String([]) when we need %j here so we use JSON.stringify([]).

Comment (schiffermtq) [reply src/decoder.js]: Thanks, fixed.

**Comment by paambaati** [comment]
@schiffermtq Thank you so much for this PR! This should also fix #1293

**Comment by paambaati** [comment]
@nicolasnoble @alexander-debater Anything we can do to get this PR reviewed/merged?

**Comment by paambaati** [comment]
@nicolasnoble @alexander-fenster Anything we can do to get this PR reviewed/merged?

**Comment by adriancable** [comment]
Bump.

**Comment by adriancable** [comment]
YES! Thank you so much.
